[pytest]

addopts = --headed
          --tracing=retain-on-failure
          --screenshot=only-on-failure
          --video=retain-on-failure
;          --base-url=http://10.60.1.177:8087
;          --base-url=http://10.60.1.37:8091/
          --base-url=http://10.60.1.49:8091/
log_cli = true
log_cli_level = debug
# ✅ 加上 asyncio 支持
asyncio_mode = auto
# ✅ 正确：告诉 pytest-asyncio 事件循环模式
[pytest-asyncio]
mode = auto


console_output_encoding = utf-8

